services: docker
dist: xenial
os: linux
language: generic

before_install:
  - docker build -t naikvarun/react-test -f ./frontend/Dockerfile.dev ./frontend
script:
  - docker run -e CI=true naikvarun/react-test test


after_success:
  - docker build -t naikvarun/multi-frontend ./frontend
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_ID}" --password-stdin
  - docker push naikvarun/multi-frontend