services: docker
dist: xenial
os: linux
language: generic

before_install:
  - docker build -t naikvarun/react-test -f ./frontend/Dockerfile.dev ./frontend
script:
  - docker run -e CI=true naikvarun/react-test test


after_success:
  - docker build -t naikvarun/multi-frontend ./frontend
  - docker build -t naikvarun/multi-server ./server
  - docker build -t naikvarun/multi-worker ./worker
  - docker build -t naikvarun/multi-nginx ./nginx
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_ID}" --password-stdin
  - docker push naikvarun/multi-frontend
  - docker push naikvarun/multi-server
  - docker push naikvarun/multi-worker
  - docker push naikvarun/multi-nginx