services: docker
dist: xenial
os: linux
language: generic

before_install:
  - docker build -t naikvarun/react-test -f ./frontend/Dockerfile.dev ./frontend
script:
  - docker run -e CI=true naikvarun/react-test test


after_success:
  - docker build -t naikvarun/multi-frontend ./frontend
  - docker build -t naikvarun/multi-server ./server
  - docker build -t naikvarun/multi-worker ./worker
  - docker build -t naikvarun/multi-nginx ./nginx
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_ID}" --password-stdin
  - docker push naikvarun/multi-frontend
  - docker push naikvarun/multi-server
  - docker push naikvarun/multi-worker
  - docker push naikvarun/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  app: "fibo-docker"
  bucket: "elasticbeanstalk-us-east-2-803550409432"
  bucket_path: "fibo-docker"
