version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pgPassword
  redis:
    image: redis
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /app/node_modules
      - ./worker:/app
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DATABASE=postgres
      - PG_USER=postgres
      - PG_PASSWORD=pgPassword
    volumes:
      - /app/node_modules
      - ./server:/app
  frontend:
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
        - 3050:80