apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-redis-deployment
spec:
  selector:
    matchLabels:
      component: app-redis
  template:
    metadata:
      labels:
        component: app-redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
