apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-postgres-deployment
spec:
  selector:
    matchLabels:
      component: app-postgres
  template:
    metadata:
      labels:
        component: app-postgres
    spec:
      containers:
      - name: app-postgres
        image: postgres
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
            subPath: postgres
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-password
                key: PG_PASSWORD
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: app-db-pvc
