apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibo-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: fibo-worker
  template:
    metadata:
      labels:
        component: fibo-worker
    spec:
      containers:
      - name: worker
        image: naikvarun/multi-worker
        env:
          - name: REDIS_HOST
            value: app-redis-clusterip-service
          - name: REDIS_PORT
            value: '6379'
